version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin <account_id>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -t myapp .
      - docker tag myapp:latest <account_id>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/myapp:latest
  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push <account_id>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/myapp:latest
